### PR TITLE
When text selected, include index number if needed

### PR DESCRIPTION
**Pull request by dracos**
This means that if the “mess” in the last paragraph of Chapter 4 is selected, the hash becomes `#mess++2` not just `#mess` which goes to the first mention. Hope that’s helpful.

(I assume the now-shared function might want to be wrapped in a IIFE but thought I’d leave that in case not.)

### CODE REVIEW

**Comment by adactio** [comment]
Brilliant! Thanks, Matthew.

**Comment by adactio** [comment]
Ah, I'm afraid there's an issue with this. I'm getting a JS error when I highlight text:

scripts.js:31 Uncaught TypeError: elements.indexOf is not a function(…)updateURL @ scripts.js:31

**Comment by dracos** [comment]
Ah, sorry, I did test it :) Which browser? I though indexOf was [widely supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf), so perhaps it’s something else, but I can’t think what. Is it any text that causes it, or just specific instance?

**Comment by dracos** [comment]
Aha, tracked it down - selecting text across multiple nodes, new PR incoming...

**Pull request merged**
